# Generated by Django 2.1 on 2018-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comments',
            field=models.ManyToManyField(blank=True, to='questions.Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=models.ManyToManyField(blank=True, to='questions.Comment'),
        ),
    ]
